jobs:
  go-test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          working_directory: go
          command: go test
workflows:
  go-test:
    jobs:
      - go-test
