version: 2.1
jobs: !include
  - filepath: ./go.yml
    jsonpath: $.jobs
  - filepath: ./py.yml
    jsonpath: $.jobs
workflows: !include
  - filepath: ./go.yml
    jsonpath: $.workflows
  - filepath: ./py.yml
    jsonpath: $.workflows
